name: e2e tests
on:
  pull_request:
  push:
concurrency:
  group: e2e-tests=full-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  e2e-tests:
    strategy:
      matrix:
        kubernetes: [ "v1.22.7" ]
    runs-on: ubuntu-latest
    env:
      KUBE_VERSION: ${{ matrix.kubernetes }}
      BRIDGE_IP: "172.17.0.1"
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Deps
        run: |
          ip a
          make test_deps
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          skipClusterCreation: "true"
      - name: e2e tests
        run: |
         make kind-create-cluster kind-e2e-tests