name: Unit tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-test-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-test-go-${{ hashFiles('**/go.sum') }}
      - name: Deps
        run: make test_deps
      - name: Run tests
        run: |
          make unit-tests
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.out